services:
  app:
    build: .
    deploy:
      mode: replicated
      replicas: 50
    restart: always
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
